<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!-- 排除基准测试子项目 -->
    <Compile Remove="Http2EchoBenchmark/**/*.cs" />
  </ItemGroup>

</Project>
